package go_fastdfs

const (
	TRACKER_PROTO_CMD_SERVICE_QUERY_STORE_WITHOUT_GROUP_ONE = 101 //上传
	TRACKER_PROTO_CMD_SERVICE_QUERY_FETCH_ONE               = 102 //下载
	STORAGE_PROTO_CMD_QUERY_FILE_INFO                       = 22  //获取文件信息

	FDFS_GROUP_NAME_MAX_LEN = 16 //groupname 16byte
	IP_ADDRESS_SIZE         = 16 //ip
	FDFS_PROTO_PKG_LEN_SIZE = 8  //port

	FDFS_LOGIC_FILE_PATH_LEN   = 10
	DFS_FILENAME_BASE64_LENGTH = 27

	TRACKER_QUERY_STORAGE_STORE_BODY_LEN = (FDFS_GROUP_NAME_MAX_LEN + IP_ADDRESS_SIZE - 1 + FDFS_PROTO_PKG_LEN_SIZE + 1)
	TRACKER_QUERY_STORAGE_FETCH_BODY_LEN = (FDFS_GROUP_NAME_MAX_LEN + IP_ADDRESS_SIZE - 1 + FDFS_PROTO_PKG_LEN_SIZE)
)
